### ISSUE TITLE
Limit the length of HTML output

### ISSUE THREAD

**Issue by bcipolli** [treasure-data/embulk-input-jira#50]
This line here outputs the full HTML document to the embulk log:
https://github.com/treasure-data/embulk-input-jira/blob/cad9f10b2e267595010a38f18e79b89fd407da9f/lib/embulk/input/jira_api/client.rb#L64

The request is also retried multiple times, and the true error (e.g. 401 Unauthorized) is lost in this tremendous logging output.

Please reduce the length of the html document being output.

**Comment by thangnc** [comment]
Thanks @bcipolli. This issue will be fixed in this PR https://github.com/treasure-data/embulk-input-jira/pull/49
